export const QUERY_CONSTANTS = {
  ENTIT_PROPERTY_COLUMNS: [
      'Entity_Property.EP_ID', 
      'Entity_Property.EP_E_ID', 
      'Entity_Property.EP_PropertyName', 
      'Entity_Property.EP_PropertyValue', 
      'Entity_Property.EP_ISACTIVE', 
      'Entity_Property.EP_ADDUSER', 
      'Entity_Property.EP_CREATEDON', 
      'Entity_Property.EP_MODIFIEDUSER', 
      'Entity_Property.EP_MODIFIEDON', 
      'Entity_Property.EP_GroupId', 
      'Entity_Property.EP_LookUpId', 
      'Entity_Property.ProductCode'
  ],
  TBL_APPLICATION_USER_COLUMNS: [
      'TblApplicationUser.TAU_Id', 
      'TblApplicationUser.TAU_MBId', 
      'TblApplicationUser.TAU_FirstName', 
      'TblApplicationUser.TAU_LastName', 
      'TblApplicationUser.TAU_MiddleName', 
      'TblApplicationUser.TAU_LoginName', 
      // 'TblApplicationUser.TAU_Password', 
      'TblApplicationUser.TAU_ProviderMasterEntityId', 
      'TblApplicationUser.TAU_EmailId', 
      'TblApplicationUser.TAU_AltEmailId', 
      'TblApplicationUser.TAU_PhoneNumber', 
      'TblApplicationUser.TAU_AltPhoneNumber', 
      'TblApplicationUser.TAU_IsActive', 
      'TblApplicationUser.TAU_IsLocked', 
      'TblApplicationUser.TAU_FailedAttemptCount', 
      'TblApplicationUser.TAU_Createdby', 
      'TblApplicationUser.TAU_CreatedOn', 
      // 'TblApplicationUser.TAU_Password1', 
      'TblApplicationUser.Modifiedon', 
      'TblApplicationUser.TAU_HasLoggedIn', 
      'TblApplicationUser.TAU_AccountLockedOn', 
      'TblApplicationUser.TAU_ModifiedBy', 
      'TblApplicationUser.TAU_IsMobileVerified', 
      'TblApplicationUser.TAU_IsEmailVerified', 
      'TblApplicationUser.TAU_MobileVerifiedModifiedOn', 
      'TblApplicationUser.TAU_EmailVerifiedModifiedOn'
  ],
};
